/**
 * youtubeTrackMatcher.js
 *
 * Automatically finds the official YouTube video for a released track,
 * given only the artist name and track title — no manual URL entry.
 *
 * Mirrors the Spotify search+match function: normalizes text, scores
 * candidates by similarity, and strongly favors "<Artist> - Topic"
 * channels, since those are auto-generated by YouTube/YouTube Music
 * directly from the metadata delivered by the distributor (Allot Lines).
 * That's the same channel type visible in the "Fake Smiles" / TrapBoyRock
 * search example — it's the reliable signal that this is the official
 * distributed upload, not a reupload, cover, or unrelated video.
 *
 * Requires YOUTUBE_API_KEY in .env (already added to Render).
 */

const SEARCH_API = 'https://www.googleapis.com/youtube/v3/search';

const ACCEPT_THRESHOLD = 0.80; // slightly looser than Spotify's 0.85 —
                                 // YouTube titles are messier (extra tags,
                                 // "(Official Audio)", etc.), but the
                                 // Topic-channel bonus below compensates.

/* ---------------------------------------------------------------------
 * TEXT NORMALIZATION
 * ------------------------------------------------------------------- */
function normalize(str) {
  if (!str) return '';
  return str
    .toLowerCase()
    .replace(/\(feat\.?[^)]*\)/g, '')
    .replace(/\[feat\.?[^\]]*\]/g, '')
    .replace(/\(official\s*(audio|video|music video|lyric video)?\)/g, '')
    .replace(/\[official\s*(audio|video|music video|lyric video)?\]/g, '')
    .replace(/\(prod\.?[^)]*\)/g, '')
    .replace(/official\s*(audio|video|music video|lyric video)/g, '')
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/* ---------------------------------------------------------------------
 * LEVENSHTEIN-BASED SIMILARITY (0 to 1)
 * ------------------------------------------------------------------- */
function levenshtein(a, b) {
  const m = a.length, n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));
  for (let i = 0; i <= m; i++) dp[i][0] = i;
  for (let j = 0; j <= n; j++) dp[0][j] = j;
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      dp[i][j] = Math.min(
        dp[i - 1][j] + 1,
        dp[i][j - 1] + 1,
        dp[i - 1][j - 1] + cost
      );
    }
  }
  return dp[m][n];
}

function similarity(a, b) {
  const na = normalize(a);
  const nb = normalize(b);
  if (!na || !nb) return 0;
  if (na === nb) return 1;
  const dist = levenshtein(na, nb);
  const maxLen = Math.max(na.length, nb.length);
  return 1 - dist / maxLen;
}

/* ---------------------------------------------------------------------
 * SCORE A SINGLE CANDIDATE
 * ------------------------------------------------------------------- */
function scoreCandidate({ trackTitle, artistName }, candidate) {
  const titleSim = similarity(trackTitle, candidate.title);
  const artistSim = similarity(artistName, candidate.channelTitle);

  // Weighted like the Spotify matcher: title matters most, artist/channel
  // match backs it up.
  let score = titleSim * 0.65 + artistSim * 0.25;

  // Strong bonus for "<Artist> - Topic" channels — this is YouTube's
  // auto-generated channel for distributed releases, the most reliable
  // signal available that this is the correct, official upload.
  const isTopicChannel = /-\s*topic\s*$/i.test(candidate.channelTitle || '');
  if (isTopicChannel) {
    score += 0.10;
    // Extra nudge if the Topic channel name itself matches the artist
    if (artistSim > 0.7) score += 0.05;
  }

  return Math.min(score, 1);
}

/* ---------------------------------------------------------------------
 * SEARCH YOUTUBE
 * ------------------------------------------------------------------- */
async function searchYouTube(query, apiKey, maxResults = 8) {
  const params = new URLSearchParams({
    part: 'snippet',
    q: query,
    type: 'video',
    videoCategoryId: '10', // Music category — cuts down unrelated results
    maxResults: String(maxResults),
    key: apiKey,
  });

  const res = await fetch(`${SEARCH_API}?${params}`);
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`YouTube search API error: ${res.status} ${body}`);
  }

  const data = await res.json();
  return (data.items || []).map((item) => ({
    videoId: item.id.videoId,
    title: item.snippet.title,
    channelTitle: item.snippet.channelTitle,
    channelId: item.snippet.channelId,
    publishedAt: item.snippet.publishedAt,
    thumbnail: item.snippet.thumbnails?.default?.url || null,
  }));
}

/* ---------------------------------------------------------------------
 * MAIN MATCH FUNCTION
 * ------------------------------------------------------------------- */
/**
 * Attempts to find the official YouTube video for a track.
 *
 * @param {string} trackTitle
 * @param {string} artistName
 * @returns {Promise<{
 *   autoAccepted: boolean,
 *   found: boolean,
 *   bestMatch: object|null,
 *   score: number|null,
 *   candidates: Array<object>  // top candidates for manual review if needed
 * }>}
 */
async function matchYouTubeVideo(trackTitle, artistName) {
  const apiKey = process.env.YOUTUBE_API_KEY;
  if (!apiKey) {
    throw new Error('YOUTUBE_API_KEY is not set in environment variables.');
  }

  const query = `${artistName} ${trackTitle}`;
  const candidates = await searchYouTube(query, apiKey);

  if (candidates.length === 0) {
    // Song simply isn't live on YouTube yet — not an error.
    return { autoAccepted: false, found: false, bestMatch: null, score: null, candidates: [] };
  }

  const scored = candidates
    .map((c) => ({ ...c, score: scoreCandidate({ trackTitle, artistName }, c) }))
    .sort((a, b) => b.score - a.score);

  const top = scored[0];
  const autoAccepted = top.score >= ACCEPT_THRESHOLD;

  return {
    autoAccepted,
    found: true,
    bestMatch: autoAccepted ? top : null,
    score: top.score,
    candidates: scored.slice(0, 5),
  };
}

module.exports = { matchYouTubeVideo, similarity, normalize };

// ---- Quick manual test: node youtubeTrackMatcher.js "Track Title" "Artist Name" ----
if (require.main === module) {
  const [trackTitle, artistName] = process.argv.slice(2);
  if (!trackTitle || !artistName) {
    console.log('Usage: node youtubeTrackMatcher.js "Track Title" "Artist Name"');
    process.exit(1);
  }
  matchYouTubeVideo(trackTitle, artistName)
    .then((result) => console.log(JSON.stringify(result, null, 2)))
    .catch((err) => console.error(err.message));
}
